# Generated by Django 4.1.4 on 2022-12-10 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_alter_message_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="num_messages",
            field=models.IntegerField(default=0),
        ),
    ]
